name = waysigns
title = WaySigns
description = Dynamic in-world HUD signboards and waypoints with universal modpack compatibility and zero entity lag.
author = SaKeL
min_minetest_version = 5.4.0
supported_games = *
optional_depends = default, signs_lib, basic_signs, street_signs, display_modpack, signs, signs_road, boards, steles, signs_rx, hiking, hiking_redo, breadcrumbs, locks, mcl_signs, jp_signs, ucsigns, xdecor, moreblocks
